appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gO5uYtAdtRRuBRovx74SAPxPtIScyJVG6PJP/fMx2i0aIum+zq4NHQxohMZRK0k7pqSX41wo/VeD6gD3L6qR6XL2pINJ+DNnw+95pLmA90x8vcJCagYRP7CDdZ7JwnIegREu7EluzNEgd94SzoUc4q0wwvZCl2qqixB6bGS+BlqYIL05PH1pESux+sTvxwJK8xsDpTopKQMrDVoiEsQX/MHe9/zuwtrjl5YERsoOq2uJEuRUBgff2V2kmLFAQ/cAUdts3fQvv1pGUgcWox5vMyPXi5nU9843BX5QK7w8lCnAs2rkMq7mMklyBm4nMCvn5xYoYpY2/eVDU2ZGwCQLOnFVRjWhjYgKPDASykURWr4nDEerfuOrOXK/ZVV5zF2Zx2fL0aBRKM6Hay+ChylWDvjNEY6PhYNrzmFkTTRzCIRau9C6dCrh89gU9FP3RvL9cD4goybVl9qhUMp8qthSKE2y8q+wVnGeTZx5C7sS8inPNP+S4WxDFqCMhxX6mtVG3qj3T40gBut+Dt8577JvMDP5xaKSsaeDZJ/L5GvU8wAdGhIK+bNFsw7qEXLF4sMAzZOwEbMZFRBx3r2OqZxndjhjv0LaNGzt0H8jZ4Vf9Vrl50b7TW8bLP7sELhY3N49XJGVhqboypL9Y+52iv4qCf9aibWaeosTQDK0yFqBKro=
conda_forge_output_validation: true
